apiVersion: v1
kind: ConfigMap
metadata:
  name: config-update
  namespace: {{ .Release.Namespace }}
data:
  SERVERNAME: {{ .Values.servername | quote }}
  DBHOST: {{ .Values.init.dbhost | quote }}
  DRUPAL_ADMIN_USER_SECRET: {{ .Chart.Annotations.secretrefsDrupalAdminUserSecret | quote }}
  DRUPAL_ADMIN_PASSWORD_SECRET: {{ .Chart.Annotations.secretrefsDrupalAdminPasswordSecret | quote }}
  DBSECRET: {{ .Chart.Annotations.secretrefsDbsecret | quote }}
  DBROOTSECRET: {{ .Chart.Annotations.secretrefsDbrootsecret | quote }}