apiVersion: v1
kind: ConfigMap
metadata:
  name: config-db-server
  namespace: {{ .Release.Namespace }}
data:
  mysqldcnf: |
    [mysqld]
    performance_schema = 0
    require-secure-transport=ON
    ssl_ca= {{ .Chart.Annotations.dbserversslca }}
    ssl_cert= {{ .Chart.Annotations.dbserversslcert }}
    ssl_key= {{ .Chart.Annotations.dbserversslkey }}
    sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    skip-log-bin
    tls_version=TLSv1.3
    transaction_isolation="READ-COMMITTED"

