apiVersion: v1
kind: Secret
metadata:
  name: selfcert
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- $externalHost := .Values.externalhost }}
{{- $cacn := printf "ca.%s" $externalHost }} 
{{- $ca := (genCA $cacn 3650) }}
{{- $dbca := (genCA .Chart.Annotations.dbcaCn 3650) }}
{{- $extern := genSignedCert .Values.externalhost nil (list $externalHost ) 365 $ca }}
{{- $dbserver := genSignedCert .Chart.Annotations.dbServerCn nil nil 365 $dbca }}
{{- $selfcert := (lookup "v1" "Secret" .Release.Namespace "selfcert").data }}
  cacert: {{ $selfcert.cacert | default ($ca.Cert | b64enc) }}
  cakey: {{ $selfcert.cakey | default ($ca.Key | b64enc) }}
  dbcacert: {{ $selfcert.dbcacert | default ($dbca.Cert | b64enc) }}
  dbcakey : {{ $selfcert.dbcakey | default ($dbca.Key | b64enc) }}
  externcert: {{ $selfcert.externcert | default ($extern.Cert | b64enc) }}
  externkey: {{ $selfcert.externkey | default ($extern.Key | b64enc) }}
  dbservercert: {{ $selfcert.dbservercert | default ($dbserver.Cert | b64enc) }}
  dbserverkey: {{ $selfcert.dbserverkey | default ($dbserver.Key | b64enc) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: externca
  namespace: {{ .Release.Namespace }}
type: tls
data:
  tls.crt: {{ $selfcert.cacert | default ($ca.Cert | b64enc) }}
