apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data: 
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "secret").data }}
  dbsecret: {{ $secret.dbsecret | default (randAlpha 24 |b64enc) }}
  dbrootsecret: {{ $secret.dbrootsecret | default (randAlpha 24 | b64enc) }}
  drupalAdminPassword: {{ $secret.drupalAdminPassword | default (randAlpha 24 | b64enc) }}
  drupalAdminUser: {{ $secret.drupalAdminUser | default (randAlpha 12 | b64enc) }}
