---
apiVersion: v1
kind: Service
metadata:
  name: civicrmdb
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: paroisse-db-impl
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
