---
apiVersion: v1
kind: Service
metadata:
  name: civicrmhttpd
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: paroisse-httpd-impl
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
